### ISSUE TITLE
Clumsy Pickaxe Perk

### ISSUE THREAD

**Issue by AmbiguousUsername** [aStableNaka/Coffee#11]
A weird pickperk is appearing that forces me to drop a random pickaxe in my inventory. After dropping, the picks disappear, unable to be used. So far, this has happened twice, dropping twice of my picks.
![image](https://user-images.githubusercontent.com/51892398/65823329-e91b3180-e208-11e9-803b-fc6e4f9fcd55.png)

**Comment by aStableNaka** [comment]
It's a sleeper routine that gets activated when the system detects self-botting. It's unlisted in the code, better policies towards self-bot detection need to be made. And the items were reclaimed.
