### ISSUE TITLE
Incorrect -illion/-illionaire suffixes

### ISSUE THREAD

**Issue by TCCGPlayz** [aStableNaka/Coffee#2]
Coffee tends to use the -illion/-illionaire suffix one level above the one it should have been, i.e. Quintillion -> Sextillion. Most places use the incorrect suffix, with one exception of the balance in `~bp` or `~bal`. The remaining all use the wrong suffix :(

**Comment by aStableNaka** [comment]
Thanks for bringing this up. It's been an issue for a while, but it's been hard to pinpoint the root of the issue.

> with one exception of the balance in ~bp or ~bal
This is extremely an useful piece of information that nobody has ever mentioned before.
I'll look into this asap

**Comment by aStableNaka** [comment]
I've found the cause of the issue

ln 54 of utils/formatting.js

`return `${ p } ${ illionLabels[ Math.floor( zed/3 ) ] }`;`
should have been
`return `${ p } ${ illionLabels[ Math.floor( zed/3 )-1 ] }`;`

The issue should now be resolved.

**Comment by TCCGPlayz** [comment]
now the -illionaire label is showing the wrong -illion suffix :rofl:

**Comment by aStableNaka** [comment]
Fixed

**Comment by TCCGPlayz** [comment]
I looked over all the locations where I can find the suffixes, and cannot find any more problems.
