### ISSUE TITLE
Local Leaderboards Needing Page #s

### ISSUE THREAD

**Issue by A5rocks** [aStableNaka/Coffee#4]
Currently, to access the local leaderboards, you need to send `~leaders local 1` or `~leaderboard local 1` or `~leaderboards local 1` or other variants. Notice the common similarity? They all have the page number!

`~leaders local` or `~leaderboard local`, etc. just results in the same output as `~leaders` or `~leaderboard`, etc.

tl;dr local leaderboards require a page number, however, as the global leaderboards show, the page number can be optional.

**Comment by aStableNaka** [comment]
Noted. I'll fix this later this week.
