### ISSUE TITLE
Command rejections

### ISSUE THREAD

**Issue by TCCGPlayz** [aStableNaka/Coffee#8]
I found some cases where Coffee does not reject command when there are missing or incorrect arguments.
`~give|use` outputs Item "undefined" not found.
`~leaderboard local` in DM outputs Global Leaderboard.
`~profile|bp|inv SomeoneThatDoesNotExist` outputs profile/balance/inventory of self.

**Comment by aStableNaka** [comment]
coffee will not reject a command. it will try to work with the parameters and if it fails, it pretends the parameters don't exist (for most commands with an overview) and goes on executing the command for a set of default parameters.

**Comment by aStableNaka** [comment]
this is a design choice. i dont like “parameter error” responses so coffee wont have many of those.
